In [ ]:
!pip install contractions
import re, string, unicodedata
import contractions
  
from bs4 import BeautifulSoup


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import nltk


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
def read_file(filepath):
    
    with open(filepath) as f:
        str_text = f.read()
    
    return str_text

In [ ]:
 len(read_file("/content/drive/My Drive/Colab Notebooks/MLProjects/twenty_years_after.txt"))

1459749

In [ ]:
print(read_file("/content/drive/My Drive/Colab Notebooks/MLProjects/twenty_years_after.txt")[:250000])







Twenty Years After
By
Alexandre Dumas


freeditorial/***

1. The Shade of Cardinal Richelieu.

In  a  splendid  chamber  of  the  Palais  Royal,  formerly  styled  the  Palais Cardinal,  a man 
was sitting in deep  reverie,  his head supported  on his hands, leaning over a gilt and inlaid 
table which was covered  with letters and papers. Behind this figure glowed a vast fireplace alive 
with leaping flames; great logs of  oak blazed and crackled on the polished brass andirons whose 
flicker shone upon  the  superb  habiliments  of  the  lonely  tenant  of  the  room,  which  was 
illumined grandly by twin candelabra rich with wax-lights.
Any one who happened  at that moment to contemplate  that red simar--the gorgeous  robe  of  
office--and  the  rich  lace,  or  who  gazed  on  that  pale  brow, bent in anxious meditation,  
might, in the solitude of  that apartment,  combined with  the  silence  of  the  ante-chambers  
and  the  measured  paces  of  the  guards upon  the  landi

In [ ]:
NovelText=read_file("/content/drive/My Drive/Colab Notebooks/MLProjects/twenty_years_after.txt")

In [ ]:
print(read_file("/content/drive/My Drive/Colab Notebooks/MLProjects/twenty_years_after.txt")[:250000])




Twenty Years After
By
Alexandre Dumas


freeditorial/***

1. The Shade of Cardinal Richelieu.

In  a  splendid  chamber  of  the  Palais  Royal,  formerly  styled  the  Palais Cardinal,  a man 
was sitting in deep  reverie,  his head supported  on his hands, leaning over a gilt and inlaid 
table which was covered  with letters and papers. Behind this figure glowed a vast fireplace alive 
with leaping flames; great logs of  oak blazed and crackled on the polished brass andirons whose 
flicker shone upon  the  superb  habiliments  of  the  lonely  tenant  of  the  room,  which  was 
illumined grandly by twin candelabra rich with wax-lights.
Any one who happened  at that moment to contemplate  that red simar--the gorgeous  robe  of  
office--and  the  rich  lace,  or  who  gazed  on  that  pale  brow, bent in anxious meditation,  
might, in the solitude of  that apartment,  combined with  the  silence  of  the  ante-chambers  
and  the  measured  paces  of  the  guards upon  the  landi

In [ ]:
def replace_html(NovelText):
    soup = BeautifulSoup(NovelText, "html.parser")
    return soup.get_text()


print(replace_html(NovelText)[:250000])




Twenty Years After
By
Alexandre Dumas


freeditorial/***

1. The Shade of Cardinal Richelieu.

In  a  splendid  chamber  of  the  Palais  Royal,  formerly  styled  the  Palais Cardinal,  a man 
was sitting in deep  reverie,  his head supported  on his hands, leaning over a gilt and inlaid 
table which was covered  with letters and papers. Behind this figure glowed a vast fireplace alive 
with leaping flames; great logs of  oak blazed and crackled on the polished brass andirons whose 
flicker shone upon  the  superb  habiliments  of  the  lonely  tenant  of  the  room,  which  was 
illumined grandly by twin candelabra rich with wax-lights.
Any one who happened  at that moment to contemplate  that red simar--the gorgeous  robe  of  
office--and  the  rich  lace,  or  who  gazed  on  that  pale  brow, bent in anxious meditation,  
might, in the solitude of  that apartment,  combined with  the  silence  of  the  ante-chambers  
and  the  measured  paces  of  the  guards upon  the  landi

In [ ]:
def replace_contractions(text):
      return contractions.fix(text)


NovelText=replace_contractions(NovelText)[:250000]

In [ ]:
def remove_numbers(text):
  text = re.sub(r'\d+', '', text)
  return text

NovelText=remove_numbers(NovelText)[:250000]
print(NovelText)




Twenty Years After
By
Alexandre Dumas


freeditorial/***

. The Shade of Cardinal Richelieu.

In  a  splendid  chamber  of  the  Palais  Royal,  formerly  styled  the  Palais Cardinal,  a man 
was sitting in deep  reverie,  his head supported  on his hands, leaning over a gilt and inlaid 
table which was covered  with letters and papers. Behind this figure glowed a vast fireplace alive 
with leaping flames; great logs of  oak blazed and crackled on the polished brass andirons whose 
flicker shone upon  the  superb  habiliments  of  the  lonely  tenant  of  the  room,  which  was 
illumined grandly by twin candelabra rich with wax-lights.
Any one who happened  at that moment to contemplate  that red simar--the gorgeous  robe  of  
office--and  the  rich  lace,  or  who  gazed  on  that  pale  brow, bent in anxious meditation,  
might, in the solitude of  that apartment,  combined with  the  silence  of  the  ante-chambers  
and  the  measured  paces  of  the  guards upon  the  landin

In [ ]:
def remove_punctuation(words):
    """Remove punctuation """
    new_word = re.sub(r'[^\w\s]', '', words)
    return new_word

NovelText=remove_punctuation(NovelText)[:250000]
print(NovelText)




Twenty Years After
By
Alexandre Dumas


freeditorial

 The Shade of Cardinal Richelieu

In  a  splendid  chamber  of  the  Palais  Royal  formerly  styled  the  Palais Cardinal  a man 
was sitting in deep  reverie  his head supported  on his hands leaning over a gilt and inlaid 
table which was covered  with letters and papers Behind this figure glowed a vast fireplace alive 
with leaping flames great logs of  oak blazed and crackled on the polished brass andirons whose 
flicker shone upon  the  superb  habiliments  of  the  lonely  tenant  of  the  room  which  was 
illumined grandly by twin candelabra rich with waxlights
Any one who happened  at that moment to contemplate  that red simarthe gorgeous  robe  of  
officeand  the  rich  lace  or  who  gazed  on  that  pale  brow bent in anxious meditation  
might in the solitude of  that apartment  combined with  the  silence  of  the  antechambers  
and  the  measured  paces  of  the  guards upon  the  landingplace  have  fancied  th

In [ ]:
def seperate_words(text):
  words=text.split()
  sepwords=[]
  for word in words:
     sepwords.append(word)
  return sepwords   



In [ ]:
tokens=seperate_words(NovelText)[:250000]

len(tokens)

41275

In [ ]:
tokens[:10]

['Twenty',
 'Years',
 'After',
 'By',
 'Alexandre',
 'Dumas',
 'freeditorial',
 'The',
 'Shade',
 'of']

Creating sequence of Tokens


In [ ]:
#train_len is  25 characters and target is 1

train_len= 26
train_sequence=[]

for i in range(train_len,len(tokens)):
   seq=tokens[i-train_len:i]
   
   train_sequence.append(seq)




In [ ]:
len(train_sequence)

41249

In [ ]:
' '.join(train_sequence[0]) 

'Twenty Years After By Alexandre Dumas freeditorial The Shade of Cardinal Richelieu In a splendid chamber of the Palais Royal formerly styled the Palais Cardinal a'

In [ ]:
print(train_sequence[0])

['Twenty', 'Years', 'After', 'By', 'Alexandre', 'Dumas', 'freeditorial', 'The', 'Shade', 'of', 'Cardinal', 'Richelieu', 'In', 'a', 'splendid', 'chamber', 'of', 'the', 'Palais', 'Royal', 'formerly', 'styled', 'the', 'Palais', 'Cardinal', 'a']


Keras Tokenizer

In [ ]:
from keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(train_sequence)

sequences = tokenizer.texts_to_sequences(train_sequence)

In [ ]:
print("Count of characters:",tokenizer.word_counts)


Count of characters: OrderedDict([('twenty', 417), ('years', 1276), ('after', 1225), ('by', 5412), ('alexandre', 5), ('dumas', 6), ('freeditorial', 7), ('the', 58602), ('shade', 87), ('of', 30220), ('cardinal', 2792), ('richelieu', 870), ('in', 17511), ('a', 21392), ('splendid', 41), ('chamber', 146), ('palais', 485), ('royal', 592), ('formerly', 281), ('styled', 126), ('man', 2652), ('was', 12064), ('sitting', 182), ('deep', 338), ('reverie', 52), ('his', 13327), ('head', 1014), ('supported', 52), ('on', 6448), ('hands', 442), ('leaning', 156), ('over', 468), ('gilt', 156), ('and', 24756), ('inlaid', 26), ('table', 364), ('which', 5707), ('covered', 205), ('with', 8680), ('letters', 182), ('papers', 52), ('behind', 416), ('this', 4550), ('figure', 130), ('glowed', 26), ('vast', 78), ('fireplace', 26), ('alive', 130), ('leaping', 26), ('flames', 26), ('great', 1222), ('logs', 26), ('oak', 52), ('blazed', 26), ('crackled', 26), ('polished', 26), ('brass', 26), ('andirons', 26), ('whose'

In [ ]:
print("Length of text:",tokenizer.document_count)


Length of text: 41249


In [ ]:
print("Character index",tokenizer.word_index)


Character index {'the': 1, 'to': 2, 'of': 3, 'and': 4, 'i': 5, 'a': 6, 'you': 7, 'in': 8, 'he': 9, 'that': 10, 'his': 11, 'was': 12, 'is': 13, 'dartagnan': 14, 'it': 15, 'not': 16, 'my': 17, 'with': 18, 'said': 19, 'had': 20, 'as': 21, 'for': 22, 'have': 23, 'but': 24, 'me': 25, 'at': 26, 'on': 27, 'him': 28, 'who': 29, 'which': 30, 'by': 31, 'be': 32, 'are': 33, 'do': 34, 'your': 35, 'this': 36, 'what': 37, 'one': 38, 'de': 39, 'no': 40, 'were': 41, 'they': 42, 'am': 43, 'monsieur': 44, 'from': 45, 'then': 46, 'so': 47, 'will': 48, 'there': 49, 'we': 50, 'well': 51, 'mazarin': 52, 'know': 53, 'her': 54, 'an': 55, 'if': 56, 'all': 57, 'cardinal': 58, 'aramis': 59, 'man': 60, 'planchet': 61, 'yes': 62, 'out': 63, 'porthos': 64, 'now': 65, 'friend': 66, 'she': 67, 'them': 68, 'when': 69, 'has': 70, 'been': 71, 'or': 72, 'would': 73, 'queen': 74, 'shall': 75, 'lord': 76, 'time': 77, 'us': 78, 'see': 79, 'himself': 80, 'replied': 81, 'ah': 82, 'dear': 83, 'very': 84, 'like': 85, 'come': 86

In [ ]:
print("Frequency of characters:",tokenizer.word_docs)

Frequency of characters: defaultdict(<class 'int'>, {'royal': 589, 'cardinal': 2630, 'twenty': 403, 'years': 1204, 'after': 1204, 'of': 21645, 'the': 30267, 'formerly': 281, 'in': 14633, 'by': 4817, 'dumas': 6, 'chamber': 146, 'a': 16516, 'freeditorial': 7, 'richelieu': 855, 'styled': 120, 'shade': 87, 'alexandre': 5, 'splendid': 41, 'palais': 463, 'man': 2493, 'was': 9810, 'sitting': 182, 'deep': 338, 'reverie': 52, 'his': 10528, 'head': 986, 'supported': 52, 'on': 5996, 'hands': 442, 'leaning': 156, 'over': 453, 'gilt': 117, 'and': 19986, 'inlaid': 26, 'table': 364, 'which': 5289, 'covered': 205, 'with': 7802, 'letters': 172, 'papers': 52, 'behind': 408, 'this': 4260, 'figure': 130, 'glowed': 26, 'vast': 78, 'fireplace': 26, 'alive': 110, 'leaping': 26, 'flames': 26, 'great': 1179, 'logs': 26, 'oak': 52, 'blazed': 26, 'crackled': 26, 'polished': 26, 'brass': 26, 'andirons': 26, 'whose': 520, 'flicker': 26, 'shone': 104, 'upon': 980, 'superb': 104, 'habiliments': 26, 'lonely': 78, 'te

In [ ]:
print(len(sequences))

41249


In [ ]:
print((sequences[0]))

[309, 117, 120, 31, 5030, 5029, 5028, 1, 1149, 3, 58, 161, 8, 6, 2320, 794, 3, 1, 271, 224, 467, 917, 1, 271, 58, 6]


In [ ]:
vocab_size=len(tokenizer.word_counts)
vocab_size

5031

Convert to Numpy matrix

In [ ]:
len(sequences)

41249

In [ ]:
len(sequences[0])

26

In [ ]:
sentence=np.array(sequences)

In [ ]:
sentence.shape

(41249, 26)

In [ ]:
sentence

array([[ 309,  117,  120, ...,  271,   58,    6],
       [ 117,  120,   31, ...,   58,    6,   60],
       [ 120,   31, 5030, ...,    6,   60,   12],
       ...,
       [  60,  474,   26, ..., 5031,    4,   46],
       [ 474,   26,    1, ...,    4,   46,  154],
       [  26,    1,  507, ...,   46,  154,    2]])

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense,Embedding,LSTM


In [ ]:
def createModel(vocab_size,seq_len):
    model = Sequential()
    model.add(Embedding(vocab_size,25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))

    model.add(Dense(vocab_size, activation='softmax'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
    model.summary()
    
    return model


In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
sentence.shape

(41249, 26)

In [ ]:
sentence

array([[ 309,  117,  120, ...,  271,   58,    6],
       [ 117,  120,   31, ...,   58,    6,   60],
       [ 120,   31, 5030, ...,    6,   60,   12],
       ...,
       [  60,  474,   26, ..., 5031,    4,   46],
       [ 474,   26,    1, ...,    4,   46,  154],
       [  26,    1,  507, ...,   46,  154,    2]])

In [ ]:
X=sentence[:,:-1]

In [ ]:
X

array([[ 309,  117,  120, ...,    1,  271,   58],
       [ 117,  120,   31, ...,  271,   58,    6],
       [ 120,   31, 5030, ...,   58,    6,   60],
       ...,
       [  60,  474,   26, ...,    6, 5031,    4],
       [ 474,   26,    1, ..., 5031,    4,   46],
       [  26,    1,  507, ...,    4,   46,  154]])

In [ ]:
Y=sentence[:,-1]

In [ ]:
Y

array([  6,  60,  12, ...,  46, 154,   2])

In [ ]:
X.shape

(41249, 25)

In [ ]:
sequence_len=len(X[1])

In [ ]:
sequence_len

25

In [ ]:
Y.shape

(41249,)

In [ ]:
Y= to_categorical(Y, num_classes=vocab_size)

IndexError: ignored

In [ ]:
model= createModel(vocab_size,sequence_len)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 25, 25)            125775    
                                                                 
 lstm_2 (LSTM)               (None, 25, 150)           105600    
                                                                 
 lstm_3 (LSTM)               (None, 150)               180600    
                                                                 
 dense_2 (Dense)             (None, 150)               22650     
                                                                 
 dense_3 (Dense)             (None, 5031)              759681    
                                                                 
Total params: 1,194,306
Trainable params: 1,194,306
Non-trainable params: 0
_________________________________________________________________


Fit Model

In [ ]:
model.fit(X, Y, batch_size=512, epochs=250,verbose=1,validation_batch_size=.20)

Generating New Text

In [ ]:
from random import randint
from pickle import load
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

In [ ]:
def generate_text(model, tokenizer, seq_len, chk_text, num_gen_words):
       
   
    output_text = []
    
      input_text = chk_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate (25 words in the video)
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict Class Probabilities for each word
     
        predict_x=model.predict(pad_encoded) 
        pred_word_ind=np.argmax(predict_x,axis=1)[0]
        #print(pred_word_ind)
        # Grab word
        pred_word = tokenizer.index_word[pred_word_ind] 

         # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
  
    return ' '.join(output_text)
        